### ISSUE TITLE
Having a hard time installing Flashcards (also did Slack crash?!) 

### ISSUE THREAD

**Issue by aviv82** [HackYourFutureBelgium/lab-antwerp-1#21]
When attempting to install Flashcards via VScode I receive the error wall below. Might have something to do with permissions on my MacOs BigSur 11.5.2 
Thank you for your help! 

➜  flashcards git:(master) ✗ npm install -g study-lenses
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/study-lenses
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/study-lenses'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/study-lenses'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/study-lenses'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Aviv/.npm/_logs/2021-09-30T20_48_56_075Z-debug.log

**Comment by gelilaa** [comment]
It looks like you're running into permission issues. If you are installing npm-packages then it might possible that you are getting an EACCES error when trying to install a package globally. This means you do not have permission to write to the directories npm uses to store global packages and commands.

this is the official suggestion https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by aviv82** [comment]
Thank you! Working on it...

**Comment by aviv82** [comment]
Fixed. i had to reinstall nvm and npm through sudo. i hope this will work long term, but as of now i can access the cards with 'study'. Thank you very much for your help!
